# src/Emilien/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /platform/{page}
    defaults:  { _controller: EmilienPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

oc_platform_view:
    path:      /platform/advert/{id}
    defaults:  { _controller: EmilienPlatformBundle:Advert:view }
    requirements:
        id: \d+

oc_platform_add:
    path:      /platform/add
    defaults:  { _controller: EmilienPlatformBundle:Advert:add }

oc_platform_edit:
    path:      /platform/edit/{id}
    defaults:  { _controller: EmilienPlatformBundle:Advert:edit }
    requirements:
        id: \d+

oc_platform_delete:
    path:      /platform/delete/{id}
    defaults:  { _controller: EmilienPlatformBundle:Advert:delete }
    requirements:
        id: \d+

oc_platform_test:
    path:      /platform/test
    defaults:  { _controller: EmilienPlatformBundle:Advert:test }